export const Images = {
  AddCard: require('../images/addCard.png'),
  Blub: require('../images/bulb.png'),
  CheckCard: require('../images/checkCard.png'),
  Chip: require('../images/chip.png'),
  ContactLess: require('../images/contactless.png'),
  Drop: require('../images/drop.png'),
  Go: require('../images/go.png'),
  HeaderLogo: require('../images/headerLogo.png'),
  Plus: require('../images/plus.png'),
  Protect: require('../images/protect.png'),
  Verify: require('../images/verify.png'),
  Card1: require('../images/Card1.png'),
  Card2: require('../images/Card2.png'),
  Card3: require('../images/Card3.png'),
  Card4: require('../images/Card4.png'),
  Card5: require('../images/Card5.png'),
  Card6: require('../images/Card6.png'),
  Card7: require('../images/Card7.png'),
  Card8: require('../images/Card8.png'),
  Card9: require('../images/Card9.png'),
};
